import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/contexts/AuthContext";
import { BurnoutHeatmap } from "@/components/BurnoutHeatmap";
import { Progress } from "@/components/ui/progress";
import { Activity, TrendingUp, AlertTriangle, CheckCircle2, RefreshCw } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { burnoutApi } from "@/lib/api";
import { useEffect, useState } from "react";
import { useToast } from "@/hooks/use-toast";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";

export default function Burnout() {
  const { user } = useAuth();
  const { toast } = useToast();
  const [burnoutData, setBurnoutData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const fetchBurnoutScore = async (forceRefresh = false) => {
    if (!user?.id) return;
    
    try {
      if (forceRefresh) setRefreshing(true);
      else setLoading(true);
      
      const score = await burnoutApi.getScore(user.id, undefined, forceRefresh);
      setBurnoutData(score);
      
      if (forceRefresh) {
        toast({
          title: "Success",
          description: "Burnout score refreshed successfully",
        });
      }
    } catch (error) {
      console.error('Error fetching burnout score:', error);
      toast({
        title: "Error",
        description: "Failed to load burnout score",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchBurnoutScore();
  }, [user?.id]);

  const getBurnoutLevel = (score: number) => {
    if (score < 40) return { level: "Low", color: "success", icon: CheckCircle2 };
    if (score < 70) return { level: "Moderate", color: "warning", icon: AlertTriangle };
    return { level: "High", color: "destructive", icon: AlertTriangle };
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-muted-foreground">Loading burnout analysis...</div>
      </div>
    );
  }

  if (!burnoutData) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-muted-foreground">No burnout data available</div>
      </div>
    );
  }

  const weeklyData = [
    { day: 'Mon', hours: 8 },
    { day: 'Tue', hours: 9 },
    { day: 'Wed', hours: 7 },
    { day: 'Thu', hours: 8 },
    { day: 'Fri', hours: 6 },
    { day: 'Sat', hours: 0 },
    { day: 'Sun', hours: 0 },
  ];

  const burnoutLevel = getBurnoutLevel(burnoutData.score || 0);
  const BurnoutIcon = burnoutLevel.icon;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold">Burnout Analysis</h1>
          <p className="text-muted-foreground mt-1">Monitor your workload and well-being</p>
        </div>
        <Button 
          onClick={() => fetchBurnoutScore(true)} 
          disabled={refreshing}
          variant="outline"
        >
          <RefreshCw className={`h-4 w-4 mr-2 ${refreshing ? 'animate-spin' : ''}`} />
          Refresh Score
        </Button>
      </div>

      <Alert variant={burnoutLevel.color === "destructive" ? "destructive" : "default"}>
        <BurnoutIcon className="h-4 w-4" />
        <AlertTitle>Burnout Level: {burnoutLevel.level}</AlertTitle>
        <AlertDescription>
          Your current burnout score is {burnoutData.score}/100. 
          {burnoutLevel.color === "destructive" && " Please consider taking a break and redistributing your workload."}
          {burnoutLevel.color === "warning" && " Monitor your workload carefully."}
          {burnoutLevel.color === "success" && " You're maintaining a healthy work-life balance!"}
        </AlertDescription>
      </Alert>

      {burnoutData.analysis && (
        <Card>
          <CardHeader>
            <CardTitle>AI Analysis</CardTitle>
            <CardDescription>Generated by {burnoutData.modelUsed}</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm leading-relaxed">{burnoutData.analysis}</p>
          </CardContent>
        </Card>
      )}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Activity className="h-4 w-4" />
              Burnout Score
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold mb-2">{burnoutData.score}/100</div>
            <Progress 
              value={burnoutData.score} 
              className="h-2" 
            />
            <p className="text-xs text-muted-foreground mt-2">
              {burnoutLevel.level} risk level
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <TrendingUp className="h-4 w-4" />
              Weekly Trend
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold capitalize mb-2">
              {burnoutData.riskLevel || 'N/A'}
            </div>
            <p className="text-xs text-muted-foreground">
              {burnoutData.riskLevel === "high" 
                ? "High stress detected" 
                : "Workload is manageable"}
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">Avg Weekly Hours</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold mb-2">
              {burnoutData.factors?.tasksInProgress || 0}
            </div>
            <p className="text-xs text-muted-foreground">
              Tasks in progress
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Activity Factors</CardTitle>
            <CardDescription>Metrics used for burnout calculation</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-sm text-muted-foreground">GitHub Commits</span>
                <span className="text-lg font-semibold">{burnoutData.factors?.commitsCount || 0}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm text-muted-foreground">Pull Requests</span>
                <span className="text-lg font-semibold">{burnoutData.factors?.pullRequestsCount || 0}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm text-muted-foreground">Tasks in Progress</span>
                <span className="text-lg font-semibold">{burnoutData.factors?.tasksInProgress || 0}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm text-muted-foreground">Completed Tasks</span>
                <span className="text-lg font-semibold">{burnoutData.factors?.completedTasks || 0}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm text-muted-foreground">Overdue Tasks</span>
                <span className="text-lg font-semibold text-destructive">{burnoutData.factors?.overdueTasks || 0}</span>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>AI Recommendations</CardTitle>
            <CardDescription>Personalized suggestions based on your activity</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {(burnoutData.recommendations || []).map((rec: string, index: number) => (
                <div key={index} className="flex gap-3 p-3 bg-muted rounded-lg">
                  <div className="flex-shrink-0 mt-0.5">
                    <CheckCircle2 className="h-5 w-5 text-primary" />
                  </div>
                  <p className="text-sm">{rec}</p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      <BurnoutHeatmap score={burnoutData.score} weeklyHours={weeklyData.map(d => d.hours)} />
    </div>
  );
}
